name: Full CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building App"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run Tests
        run: echo "Testing App"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploy
        run: echo "Deploying App"